checks:
    javascript: true

filter:
  paths: ["lib/*"]
  excluded_paths:
    - test/*

build:
  environment:
    node:
      version: v16

  tests:
    override:
      -
        command: 'yarn install && yarn run test'
        coverage:
          file: 'coverage/clover.xml'
          format: 'clover'
