checks:
  javascript: true

filter:
  paths: ['lib/*']
  excluded_paths:
    - tests/*
    - examples/*

build:
  environment:
    node:
      version: v16

  dependencies:
    override:
      - command: 'npm --global install yarn'
      - command: 'yarn install'

  tests:
    override:
      - command: 'yarn run test'
        coverage:
          file: 'coverage/clover.xml'
          format: 'clover'
