name: Publish to NPM
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: 🔧 Install dependencies
        run: yarn install

      - name: 🔧 Build
        run: yarn build

      - name: 📦 Publish package on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: 📦 Publish package on GPR
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}